export const ADD_SALARY_REQUEST = "ADD_SALARY_REQUEST";
export const ADD_SALARY_SUCCESS = "ADD_SALARY_SUCCESS";
export const ADD_SALARY_FAILURE = "ADD_SALARY_FAILURE";

export const MANAGE_LEAVE_TYPES_REQUEST = "MANAGE_LEAVE_TYPES_REQUEST";
export const MANAGE_LEAVE_TYPES_SUCCESS = "MANAGE_LEAVE_TYPES_SUCCESS";
export const MANAGE_LEAVE_TYPES_FAILURE = "MANAGE_LEAVE_TYPES_FAILURE";

export const CHANGE_LEAVE_TYPES_REQUEST = "CHANGE_LEAVE_TYPES_REQUEST";
export const CHANGE_LEAVE_TYPES_SUCCESS = "CHANGE_LEAVE_TYPES_SUCCESS";
export const CHANGE_LEAVE_TYPES_FAILURE = "CHANGE_LEAVE_TYPES_FAILURE";

export const GET_LEAVE_REQUESTS_REQUEST = "GET_LEAVE_REQUESTS_REQUEST";
export const GET_LEAVE_REQUESTS_SUCCESS = "GET_LEAVE_REQUESTS_SUCCESS";
export const GET_LEAVE_REQUESTS_FAILURE = "GET_LEAVE_REQUESTS_FAILURE";

export const APPROVE_LEAVE_REQUEST = "APPROVE_LEAVE_REQUEST";
export const APPROVE_LEAVE_SUCCESS = "APPROVE_LEAVE_SUCCESS";
export const APPROVE_LEAVE_FAILURE = "APPROVE_LEAVE_FAILURE";

export const REJECT_LEAVE_REQUEST = "REJECT_LEAVE_REQUEST";
export const REJECT_LEAVE_SUCCESS = "REJECT_LEAVE_SUCCESS";
export const REJECT_LEAVE_FAILURE = "REJECT_LEAVE_FAILURE";

export const GET_EMP_INFO_REQUEST = "GET_EMP_INFO_REQUEST";
export const GET_EMP_INFO_SUCCESS = "GET_EMP_INFO_SUCCESS";
export const GET_EMP_INFO_FAILURE = "GET_EMP_INFO_FAILURE";

export const UPDATE_EMP_INFO_REQUEST = "UPDATE_EMP_INFO_REQUEST";
export const UPDATE_EMP_INFO_SUCCESS = "UPDATE_EMP_INFO_SUCCESS";
export const UPDATE_EMP_INFO_FAILURE = "UPDATE_EMP_INFO_FAILURE";