export const GET_SALARY_DETAILS_REQUEST = "GET_SALARY_DETAILS_REQUEST";
export const GET_SALARY_DETAILS_SUCCESS = "GET_SALARY_DETAILS_SUCCESS";
export const GET_SALARY_DETAILS_FAILURE = "GET_SALARY_DETAILS_FAILURE";
