export const GET_SELF_INFO_REQUEST = "GET_SELF_INFO_REQUEST";
export const GET_SELF_INFO_SUCCESS = "GET_SELF_INFO_SUCCESS";
export const GET_SELF_INFO_FAILURE = "GET_SELF_INFO_FAILURE";

export const UPDATE_SELF_INFO_REQUEST = "UPDATE_SELF_INFO_REQUEST";
export const UPDATE_SELF_INFO_SUCCESS = "UPDATE_SELF_INFO_SUCCESS";
export const UPDATE_SELF_INFO_FAILURE = "UPDATE_SELF_INFO_FAILURE";

export const ADD_INFO_REQUEST = "ADD_INFO_REQUEST";
export const ADD_INFO_SUCCESS = "ADD_INFO_SUCCESS";
export const ADD_INFO_FAILURE = "ADD_INFO_FAILURE";

export const UPLOAD_FILES_REQUEST = "UPLOAD_FILES_REQUEST";
export const UPLOAD_FILES_SUCCESS = "UPLOAD_FILES_SUCCESS";
export const UPLOAD_FILES_FAILURE = "UPLOAD_FILES_FAILURE";

export const GET_LEAVES_REQUEST = "GET_LEAVES_REQUEST";
export const GET_LEAVES_SUCCESS = "GET_LEAVES_SUCCESS";
export const GET_LEAVES_FAILURE = "GET_LEAVES_FAILURE";

export const CANCEL_LEAVE_REQUEST = "CANCEL_LEAVE_REQUEST";
export const CANCEL_LEAVE_SUCCESS = "CANCEL_LEAVE_SUCCESS";
export const CANCEL_LEAVE_FAILURE = "CANCEL_LEAVE_FAILURE";

export const GET_LEAVE_TYPES_REQUEST = "GET_LEAVE_TYPES_REQUEST";
export const GET_LEAVE_TYPES_SUCCESS = "GET_LEAVE_TYPES_SUCCESS";
export const GET_LEAVE_TYPES_FAILURE = "GET_LEAVE_TYPES_FAILURE";

export const MARK_LEAVE_REQUEST = "MARK_LEAVE_REQUEST";
export const MARK_LEAVE_SUCCESS = "MARK_LEAVE_SUCCESS";
export const MARK_LEAVE_FAILURE = "MARK_LEAVE_FAILURE";

